Project #1 – Organizing and Summarizing Air Quality Data
Client: UNMC Water, Climate and Health Group  

This notebook analyzes AirPurple air quality data collected across Nebraska
from February 2024 to March 2025. The purpose of this analysis is to identify
air pollution locations, evaluate AQI health risks, and assess how temperature,
humidity, and altitude impact air quality.

In [6]:
import pandas as pd

In [7]:
# Load the CSV file 

air_data = pd.read_csv("AirQuality_Daily_StudentVersion.csv")

# Turn data into a dataframe
air_data = pd.DataFrame(air_data)


# Preview first 5 rows to confirm the data loaded correctly
air_data.head(5)

,date,monitor_index,humidity,pressure,temperature,voc,analog_input,pm2.5_alt,pm1.0_atm,pm2.5_atm,pm10.0_atm,sensor.latitude,sensor.longitude,sensor.altitude,sensor.name
0,02/23/24,195089,14.377667,912.884333,62.266667,51.998667,0.051333,0.1000,0.000000,0.002500,0.039667,40.050922,-101.533570,3005,Swnphd-Benklemen
1,02/23/24,195365,12.223600,926.403000,71.193400,64.920800,0.000000,0.1800,0.004800,0.020000,0.176000,40.200330,-100.639885,2576,Swnphd-mccook
2,02/23/24,195541,20.095750,905.670750,61.008250,68.307000,0.020000,0.1625,0.004125,0.014812,0.063937,41.128284,-101.720220,3220,Swnphd-ogallala
3,02/24/24,195089,25.368000,911.708833,51.462458,91.176750,0.052667,0.4375,0.099542,0.170667,0.355208,40.050922,-101.533570,3005,Swnphd-Benklemen
4,02/24/24,195365,23.703083,925.282125,56.818208,107.863708,0.000000,0.4750,0.099208,0.231687,0.548583,40.200330,-100.639885,2576,Swnphd-mccook

In [8]:
# Show all column names to see the titles of each columns
air_data.columns

Index(['date', 'monitor_index', 'humidity', 'pressure', 'temperature', 'voc',
       'analog_input', 'pm2.5_alt', 'pm1.0_atm', 'pm2.5_atm', 'pm10.0_atm',
       'sensor.latitude', 'sensor.longitude', 'sensor.altitude',
       'sensor.name'],
      dtype='object')

In [9]:
# Group data by sensor.name and count number of observations per sensor
sensor_counts = air_data.groupby(["sensor.name"]).size()

# Print the counts
print(sensor_counts)

sensor.name
#16 - Richardson County Courthouse                              318
#17 - Otoe County                                               302
#18 - Southeast District Health Department- Tecumseh            183
Ainsworth Public School #9                                      368
Broken Bow                                                      368
Buffalo County TRPHD #26                                        359
ELVPHD Norfolk HD 4                                             171
ELVPHD Tekamah HD 3                                             202
ELVPHD Wisner HD 5                                              357
FCHD-YPS                                                        365
Laurel High School                                              172
Loup Basin Public Health Department                             389
Lower Niobrara NRD Butte 10                                     371
NCDHD O'Neill #11                                               226
PHS Fairbury JCHL 13                                            348
SWNPHD-Imerial                                                  284
South Heartland District Health Dept. Hastings office           377
South Heartland District Health Dept. Superior City Building    286
Swnphd-Benklemen                                                388
Swnphd-mccook                                                   390
Swnphd-ogallala                                                 376
TRPHD Dawson Co. Courthouse 25                                  387
TRPHD Harlan Co. Courthouse 24                                  367
Three Rivers Public Health Department                           377
WCDHD Arthur High School 28                                     320
WCDHD City Building                                             103
WCDHD Thedford Library 29                                       147
dtype: int64

Client Question 1: What are the 5 locations with highest mean and median concentrations of VOC, PM2.5, PM10?

In [10]:
# Group by sensor.name and compute mean and median for VOC, PM2.5, and PM10
grouped_data = air_data.groupby("sensor.name").agg(
    voc_mean=("voc", "mean"),
    voc_median=("voc", "median"),
    pm25_mean=("pm2.5_atm", "mean"),
    pm25_median=("pm2.5_atm", "median"),
    pm10_mean=("pm10.0_atm", "mean"),
    pm10_median=("pm10.0_atm", "median")
)

# Print the summary table
print(grouped_data.head())

                                                      voc_mean  voc_median  \
sensor.name
#16 - Richardson County Courthouse                   86.758650   84.470500
#17 - Otoe County                                   251.427296  234.953542
#18 - Southeast District Health Department- Tec...  196.150771  138.582583
Ainsworth Public School #9                          219.200274  217.897500
Broken Bow                                          158.285807  138.559646

                                                     pm25_mean  pm25_median  \
sensor.name
#16 - Richardson County Courthouse                  700.127342    11.977344
#17 - Otoe County                                     9.755345     7.687563
#18 - Southeast District Health Department- Tec...  613.175352    10.322875
Ainsworth Public School #9                           10.697058     8.389740
Broken Bow                                          928.710593    36.050240

                                                     pm10_mean  pm10_median
sensor.name
#16 - Richardson County Courthouse                  701.632446    13.305615
#17 - Otoe County                                    11.671141     9.398875
#18 - Southeast District Health Department- Tec...  614.227248    11.433729
Ainsworth Public School #9                           12.390708     9.449781
Broken Bow                                          929.678512    43.179094

In [11]:
# Top 5 sensors by VOC mean
top5_voc_mean = grouped_data.sort_values(by="voc_mean", ascending=False).head(5)
print(top5_voc_mean)

# Top 5 sensors by VOC median
top5_voc_median = grouped_data.sort_values(by="voc_median", ascending=False).head(5)
print(top5_voc_median)


# Top 5 sensors by PM2.5 mean
top5_pm25_mean = grouped_data.sort_values(by="pm25_mean", ascending=False).head(5)
print(top5_pm25_mean)

# Top 5 sensors by PM2.5 median
top5_pm25_median = grouped_data.sort_values(by="pm25_median", ascending=False).head(5)
print(top5_pm25_median)

# Top 5 sensors by PM10 mean
top5_pm10_mean = grouped_data.sort_values(by="pm10_mean", ascending=False).head(5)
print(top5_pm10_mean)

# Top 5 sensors by PM10 median
top5_pm10_median = grouped_data.sort_values(by="pm10_median", ascending=False).head(5)
print(top5_pm10_median)

                                         voc_mean  voc_median   pm25_mean  \
sensor.name
Swnphd-ogallala                        399.434240  423.082292   10.396579
FCHD-YPS                               372.462720  375.383500    9.167842
Three Rivers Public Health Department  370.216208  376.810167    9.601760
ELVPHD Norfolk HD 4                    360.833744  368.580500   13.369492
Swnphd-mccook                          353.941581  381.468479  123.011622

                                       pm25_median   pm10_mean  pm10_median
sensor.name
Swnphd-ogallala                           3.518510   11.347889     4.149646
FCHD-YPS                                  5.838188   11.138241     7.442750
Three Rivers Public Health Department     6.860375   11.226492     8.239708
ELVPHD Norfolk HD 4                       9.706229   15.969341    11.474708
Swnphd-mccook                             4.582281  124.227336     5.372073
                                         voc_mean  voc_median   pm25_mean  \
sensor.name
Swnphd-ogallala                        399.434240  423.082292   10.396579
Swnphd-mccook                          353.941581  381.468479  123.011622
Three Rivers Public Health Department  370.216208  376.810167    9.601760
FCHD-YPS                               372.462720  375.383500    9.167842
ELVPHD Norfolk HD 4                    360.833744  368.580500   13.369492

                                       pm25_median   pm10_mean  pm10_median
sensor.name
Swnphd-ogallala                           3.518510   11.347889     4.149646
Swnphd-mccook                             4.582281  124.227336     5.372073
Three Rivers Public Health Department     6.860375   11.226492     8.239708
FCHD-YPS                                  5.838188   11.138241     7.442750
ELVPHD Norfolk HD 4                       9.706229   15.969341    11.474708
                                                      voc_mean  voc_median  \
sensor.name
Broken Bow                                          158.285807  138.559646
#16 - Richardson County Courthouse                   86.758650   84.470500
#18 - Southeast District Health Department- Tec...  196.150771  138.582583
NCDHD O'Neill #11                                   283.633000  238.404833
Swnphd-mccook                                       353.941581  381.468479

                                                     pm25_mean  pm25_median  \
sensor.name
Broken Bow                                          928.710593    36.050240
#16 - Richardson County Courthouse                  700.127342    11.977344
#18 - Southeast District Health Department- Tec...  613.175352    10.322875
NCDHD O'Neill #11                                   164.495078     7.251208
Swnphd-mccook                                       123.011622     4.582281

                                                     pm10_mean  pm10_median
sensor.name
Broken Bow                                          929.678512    43.179094
#16 - Richardson County Courthouse                  701.632446    13.305615
#18 - Southeast District Health Department- Tec...  614.227248    11.433729
NCDHD O'Neill #11                                   166.132578     8.427437
Swnphd-mccook                                       124.227336     5.372073
                                                      voc_mean  voc_median  \
sensor.name
Broken Bow                                          158.285807  138.559646
#16 - Richardson County Courthouse                   86.758650   84.470500
#18 - Southeast District Health Department- Tec...  196.150771  138.582583
ELVPHD Norfolk HD 4                                 360.833744  368.580500
ELVPHD Wisner HD 5                                  102.291126  100.709271

                                                     pm25_mean  pm25_median  \
sensor.name
Broken Bow                                          928.710593    36.050240
#16 - Richardson County Courthouse                  700.127342    11.977344
#18 - Southeast District Health Department- Tec...  613.175352    10.322875
ELVPHD Norfolk HD 4                                  13.369492     9.706229
ELVPHD Wisner HD 5                                   11.154420     8.464583

                                                     pm10_mean  pm10_median
sensor.name
Broken Bow                                          929.678512    43.179094
#16 - Richardson County Courthouse                  701.632446    13.305615
#18 - Southeast District Health Department- Tec...  614.227248    11.433729
ELVPHD Norfolk HD 4                                  15.969341    11.474708
ELVPHD Wisner HD 5                                   14.462116    10.935958
                                                      voc_mean  voc_median  \
sensor.name
Broken Bow                                          158.285807  138.559646
#16 - Richardson County Courthouse                   86.758650   84.470500
#18 - Southeast District Health Department- Tec...  196.150771  138.582583
NCDHD O'Neill #11                                   283.633000  238.404833
Swnphd-mccook                                       353.941581  381.468479

                                                     pm25_mean  pm25_median  \
sensor.name
Broken Bow                                          928.710593    36.050240
#16 - Richardson County Courthouse                  700.127342    11.977344
#18 - Southeast District Health Department- Tec...  613.175352    10.322875
NCDHD O'Neill #11                                   164.495078     7.251208
Swnphd-mccook                                       123.011622     4.582281

                                                     pm10_mean  pm10_median
sensor.name
Broken Bow                                          929.678512    43.179094
#16 - Richardson County Courthouse                  701.632446    13.305615
#18 - Southeast District Health Department- Tec...  614.227248    11.433729
NCDHD O'Neill #11                                   166.132578     8.427437
Swnphd-mccook                                       124.227336     5.372073
                                                      voc_mean  voc_median  \
sensor.name
Broken Bow                                          158.285807  138.559646
#16 - Richardson County Courthouse                   86.758650   84.470500
ELVPHD Norfolk HD 4                                 360.833744  368.580500
#18 - Southeast District Health Department- Tec...  196.150771  138.582583
ELVPHD Wisner HD 5                                  102.291126  100.709271

                                                     pm25_mean  pm25_median  \
sensor.name
Broken Bow                                          928.710593    36.050240
#16 - Richardson County Courthouse                  700.127342    11.977344
ELVPHD Norfolk HD 4                                  13.369492     9.706229
#18 - Southeast District Health Department- Tec...  613.175352    10.322875
ELVPHD Wisner HD 5                                   11.154420     8.464583

                                                     pm10_mean  pm10_median
sensor.name
Broken Bow                                          929.678512    43.179094
#16 - Richardson County Courthouse                  701.632446    13.305615
ELVPHD Norfolk HD 4                                  15.969341    11.474708
#18 - Southeast District Health Department- Tec...  614.227248    11.433729
ELVPHD Wisner HD 5                                   14.462116    10.935958

Answers to the question 1 from above table: 

The locations that repeatedly appear at the top for VOC, PM2.5, and PM10 are Swnphd-ogallala, FCHD-YPS, Three Rivers Public Health Department,ELVPHD Norfolk HD 4,Swnphd-mccook.These areas rank highly across multiple pollutants, indicating sustained elevated air pollutant concentrations. Specifically, Swnphd-mccook shows exceptionally high particulate matter concentrations, and Swnphd-ogallala and FCHD-YPS exhibit consistently high VOC levels. These locations represent potential air quality hotspots.


Other locations are Broken Bow, Richardson County Courthouse which spike for only one pollutant, but not across all three.

Client question 2: On what days did the maximum values occur and where did this maximums occur?

In [12]:
# Find the maximum VOC value.
highest_voc = air_data["voc"].max()

# find the date and sensor of the maximum VOC
max_voc_event = air_data[air_data["voc"] == highest_voc][
    ["date", "sensor.name", "voc"]
]

print(max_voc_event)

          date      sensor.name          voc
2391  06/24/24  Swnphd-ogallala  1209.931571

In [13]:
#now we find the maximum pm2.5 value

highest_pm25 = air_data["pm2.5_atm"].max()

#we find the date and sensor of the maximum pm2.5
air_data[air_data["pm2.5_atm"] == highest_pm25][
    ["date", "sensor.name", "pm2.5_atm"]
]

          date                         sensor.name    pm2.5_atm
7561  02/18/25  #16 - Richardson County Courthouse  3782.823313

In [14]:
#now we find the maximum pm10.0 value

highest_pm10 = air_data["pm10.0_atm"].max()

#we find the date and sensor of the maximum pm10.0

air_data[air_data["pm10.0_atm"] == highest_pm10][
    ["date", "sensor.name", "pm10.0_atm"]
]

          date                         sensor.name   pm10.0_atm
7561  02/18/25  #16 - Richardson County Courthouse  3784.682542

The above code generates the values with date and location. Max VOC: June 24, 2024 at Swnphd-ogallala, Max PM2.5: February 18, 2025 at #16 Richardson County Courthouse, Max PM10: February 18, 2025 at #16 Richardson County Courthouse.

Client Question 3: Does humidity and temperature have a noticeable effect on air quality?

Uase provided categories for humiditry: Low humidity occurs at a relative humidity less than 50%, high humidity occurs at a relative humidity between 50 and 80%, very high humidity occurs at a relative humidity above 80%.

In [15]:

#define a function that assigns the humidity levels

def humidity_category(humidity):
    if humidity < 50:
        return "Low"
    elif 50 <= humidity <= 80:
        return "High"
    else:
        return "Very High"

#Apply altitude categories to the full dataset
air_data["humidity_category"] = air_data["humidity"].apply(humidity_category)

air_data.head(30)

,date,monitor_index,humidity,pressure,temperature,voc,analog_input,pm2.5_alt,pm1.0_atm,pm2.5_atm,pm10.0_atm,sensor.latitude,sensor.longitude,sensor.altitude,sensor.name,humidity_category
0,02/23/24,195089,14.377667,912.884333,62.266667,51.998667,0.051333,0.100000,0.000000,0.002500,0.039667,40.050922,-101.533570,3005,Swnphd-Benklemen,Low
1,02/23/24,195365,12.223600,926.403000,71.193400,64.920800,0.000000,0.180000,0.004800,0.020000,0.176000,40.200330,-100.639885,2576,Swnphd-mccook,Low
2,02/23/24,195541,20.095750,905.670750,61.008250,68.307000,0.020000,0.162500,0.004125,0.014812,0.063937,41.128284,-101.720220,3220,Swnphd-ogallala,Low
3,02/24/24,195089,25.368000,911.708833,51.462458,91.176750,0.052667,0.437500,0.099542,0.170667,0.355208,40.050922,-101.533570,3005,Swnphd-Benklemen,Low
4,02/24/24,195365,23.703083,925.282125,56.818208,107.863708,0.000000,0.475000,0.099208,0.231687,0.548583,40.200330,-100.639885,2576,Swnphd-mccook,Low
5,02/24/24,195541,29.082083,903.069000,52.063833,96.558875,0.020000,0.441667,0.053417,0.118813,0.241583,41.128284,-101.720220,3220,Swnphd-ogallala,Low
6,02/25/24,195089,20.633125,906.199667,54.271000,98.027208,0.053542,0.741667,0.186167,0.536167,1.272979,40.050922,-101.533570,3005,Swnphd-Benklemen,Low
7,02/25/24,195365,17.341708,919.602625,61.311000,104.390083,0.000000,0.941667,0.543604,0.907917,1.609354,40.200330,-100.639885,2576,Swnphd-mccook,Low
8,02/25/24,195541,23.904208,897.842417,55.670833,89.880250,0.020000,0.791667,0.283729,0.602854,0.985021,41.128284,-101.720220,3220,Swnphd-ogallala,Low
9,02/26/24,195089,18.948792,901.163792,57.556792,83.773958,0.053292,0.850000,0.279896,0.744229,1.834646,40.050922,-101.533570,3005,Swnphd-Benklemen,Low
10,02/26/24,195365,14.355708,914.554458,65.521375,81.122042,0.000000,1.037500,0.593521,1.106292,2.125104,40.200330,-100.639885,2576,Swnphd-mccook,Low
11,02/26/24,195541,21.369500,892.512042,58.236000,78.583458,0.020000,1.104167,0.785479,1.191312,1.623917,41.128284,-101.720220,3220,Swnphd-ogallala,Low
12,02/27/24,195089,32.420500,897.259917,44.229500,86.679000,0.056708,1.000000,0.547396,1.066583,1.951062,40.050922,-101.533570,3005,Swnphd-Benklemen,Low
13,02/27/24,195365,28.790542,910.613708,48.362458,78.246542,0.000000,1.250000,0.848125,1.547187,2.770917,40.200330,-100.639885,2576,Swnphd-mccook,Low
14,02/27/24,195541,33.190292,890.106167,44.052875,75.244708,0.020000,0.862500,0.389104,0.753687,1.073125,41.128284,-101.720220,3220,Swnphd-ogallala,Low
15,02/28/24,195089,31.286208,914.647708,36.003458,93.794458,0.057583,1.087500,0.810396,1.325042,1.949938,40.050922,-101.533570,3005,Swnphd-Benklemen,Low
16,02/28/24,195365,27.959333,929.410458,36.973000,107.253500,0.000000,0.870833,0.448792,0.896479,1.506667,40.200330,-100.639885,2576,Swnphd-mccook,Low
17,02/28/24,195541,30.081417,905.696417,37.306750,93.267000,0.020000,1.012500,0.697833,1.220042,1.662771,41.128284,-101.720220,3220,Swnphd-ogallala,Low
18,02/29/24,195089,24.122167,910.530792,48.045917,83.086000,0.055917,1.008333,0.607854,1.013375,1.674146,40.050922,-101.533570,3005,Swnphd-Benklemen,Low
19,02/29/24,195319,12.470333,947.636667,65.571444,60.848333,0.000000,2.466667,3.050167,4.065167,4.894167,40.589070,-98.383190,1920,South Heartland District Health Dept. Hastings...,Low
20,02/29/24,195365,20.251458,925.426917,52.828500,81.629750,0.000000,18.683333,19.920479,28.601292,35.032208,40.200330,-100.639885,2576,Swnphd-mccook,Low
21,02/29/24,195541,21.105417,901.840542,55.316583,82.189667,0.020000,1.066667,0.571479,1.027146,1.630500,41.128284,-101.720220,3220,Swnphd-ogallala,Low
22,03/01/24,195089,29.860375,905.012625,55.290583,79.580458,0.053417,8.216667,11.810042,15.402458,17.008104,40.050922,-101.533570,3005,Swnphd-Benklemen,Low
23,03/01/24,195319,12.364333,944.002000,81.597000,79.131667,0.000000,0.966667,0.591833,0.860333,1.058333,40.589070,-98.383190,1920,South Heartland District Health Dept. Hastings...,Low
24,03/01/24,195333,16.080667,923.753333,73.311333,82.911000,0.010000,4.200000,5.483167,6.878667,7.666167,40.780205,-99.740486,2392,TRPHD Dawson Co. Courthouse 25,Low
25,03/01/24,195365,33.206708,919.613875,56.390292,65.596333,0.000000,11.316667,15.229479,21.617083,25.319500,40.200330,-100.639885,2576,Swnphd-mccook,Low
26,03/01/24,195383,10.923750,929.638750,84.341750,65.896500,0.050000,4.425000,5.473375,7.385125,9.250750,41.779380,-99.138040,2174,Loup Basin Public Health Department,Low
27,03/01/24,195541,22.815250,896.491708,60.588875,85.274375,0.019333,4.183333,5.381896,7.159229,8.121854,41.128284,-101.720220,3220,Swnphd-ogallala,Low
28,03/02/24,195089,20.172208,900.441583,61.454792,79.709833,0.051250,2.383333,2.616437,3.557750,4.264896,40.050922,-101.533570,3005,Swnphd-Benklemen,Low
29,03/02/24,195333,55.604125,922.319750,48.770500,93.602083,0.010000,18.295833,22.102708,33.433750,37.774771,40.780205,-99.740486,2392,TRPHD Dawson Co. Courthouse 25,High

Use provided categories for temperature: temperature < 32 "Below Freezing", 32 - 50 "Cool", 51-70 "Warm", and >70 "Hot".

In [16]:
# Define temperature category function
def temperature_category(x):
    if x < 32:
        return "Below Freezing"
    elif 32 <= x <= 50:
        return "Cool"
    elif 51 <= x <= 70:
        return "Warm"
    else:
        return "Hot"


#Apply temperature categories to the full dataset
air_data["temperature_category"] = air_data["temperature"].apply(temperature_category)

air_data.head(10)

,date,monitor_index,humidity,pressure,temperature,voc,analog_input,pm2.5_alt,pm1.0_atm,pm2.5_atm,pm10.0_atm,sensor.latitude,sensor.longitude,sensor.altitude,sensor.name,humidity_category,temperature_category
0,02/23/24,195089,14.377667,912.884333,62.266667,51.998667,0.051333,0.100000,0.000000,0.002500,0.039667,40.050922,-101.533570,3005,Swnphd-Benklemen,Low,Warm
1,02/23/24,195365,12.223600,926.403000,71.193400,64.920800,0.000000,0.180000,0.004800,0.020000,0.176000,40.200330,-100.639885,2576,Swnphd-mccook,Low,Hot
2,02/23/24,195541,20.095750,905.670750,61.008250,68.307000,0.020000,0.162500,0.004125,0.014812,0.063937,41.128284,-101.720220,3220,Swnphd-ogallala,Low,Warm
3,02/24/24,195089,25.368000,911.708833,51.462458,91.176750,0.052667,0.437500,0.099542,0.170667,0.355208,40.050922,-101.533570,3005,Swnphd-Benklemen,Low,Warm
4,02/24/24,195365,23.703083,925.282125,56.818208,107.863708,0.000000,0.475000,0.099208,0.231687,0.548583,40.200330,-100.639885,2576,Swnphd-mccook,Low,Warm
5,02/24/24,195541,29.082083,903.069000,52.063833,96.558875,0.020000,0.441667,0.053417,0.118813,0.241583,41.128284,-101.720220,3220,Swnphd-ogallala,Low,Warm
6,02/25/24,195089,20.633125,906.199667,54.271000,98.027208,0.053542,0.741667,0.186167,0.536167,1.272979,40.050922,-101.533570,3005,Swnphd-Benklemen,Low,Warm
7,02/25/24,195365,17.341708,919.602625,61.311000,104.390083,0.000000,0.941667,0.543604,0.907917,1.609354,40.200330,-100.639885,2576,Swnphd-mccook,Low,Warm
8,02/25/24,195541,23.904208,897.842417,55.670833,89.880250,0.020000,0.791667,0.283729,0.602854,0.985021,41.128284,-101.720220,3220,Swnphd-ogallala,Low,Warm
9,02/26/24,195089,18.948792,901.163792,57.556792,83.773958,0.053292,0.850000,0.279896,0.744229,1.834646,40.050922,-101.533570,3005,Swnphd-Benklemen,Low,Warm

In [17]:
# Group by humidity and temperature categories and calculate mean pollutant values
weather_grouped = air_data.groupby(["humidity_category", "temperature_category"]).agg(
    voc_mean=("voc", "mean"),
    pm25_mean=("pm2.5_atm", "mean"),
    pm10_mean=("pm10.0_atm", "mean")
)

print(weather_grouped)

                                          voc_mean   pm25_mean   pm10_mean
humidity_category temperature_category
High              Below Freezing        180.465221  219.988463  222.407359
                  Cool                  223.382793  189.676348  192.089116
                  Hot                   280.580732   21.592081   23.408389
                  Warm                  244.123474   68.266242   69.125519
Low               Below Freezing        265.498951  279.768902  282.112621
                  Cool                  299.457166  136.594457  137.859993
                  Hot                   283.225167   22.849731   24.353956
                  Warm                  261.240435   86.494960   87.422966
Very High         Below Freezing               NaN    6.639000   24.704500
                  Cool                   42.101733    5.290655    6.331810
                  Hot                    10.111631  605.960565  608.884894
                  Warm                    4.613115    4.667355    5.619743

Air quality data were grouped by humidity and temperature categories to evaluate whether meteorological conditions have a noticeable effect on pollutant concentrations. The results show clear variation in mean VOC, PM2.5, and PM10 values across different humidity and temperature combinations.

In [18]:
# Filter PM2.5 values in the AQI "Unhealthy for Sensitive Groups" range
pm25_usg = air_data[
    (air_data["pm2.5_atm"] >= 35.5) &
    (air_data["pm2.5_atm"] <= 55.4)
]

#Select only date, sensor, and PM2.5 columns and sort by date
pm25_usg_events = pm25_usg[
    ["date", "sensor.name", "pm2.5_atm"]
].sort_values("date")

#Display first 10 events
pm25_usg_events.head(10)

          date                                        sensor.name  pm2.5_atm
6730  01/09/25  South Heartland District Health Dept. Superior...  39.975313
6721  01/09/25                               PHS Fairbury JCHL 13  41.249042
6720  01/09/25                                  #17 - Otoe County  35.746292
7304  02/06/25                           Buffalo County TRPHD #26  39.639000
7511  02/15/25  South Heartland District Health Dept. Superior...  38.148875
7508  02/15/25              Three Rivers Public Health Department  37.249500
7503  02/15/25                         Ainsworth Public School #9  38.737979
7501  02/15/25                               PHS Fairbury JCHL 13  42.358938
7498  02/15/25                          WCDHD Thedford Library 29  36.138729
7493  02/15/25                                 ELVPHD Wisner HD 5  51.984812

In [20]:
# Filter PM10 values in the AQI "Unhealthy for Sensitive Groups" range
pm10_usg = air_data[
    (air_data["pm10.0_atm"] >= 155) &
    (air_data["pm10.0_atm"] <= 254)
]

#Select only date, sensor, and PM10 columns and sort by date
pm10_usg_events = pm10_usg[
    ["date", "sensor.name", "pm10.0_atm"]
].sort_values("date")

#Display first 10 events
pm10_usg_events.head(10)

          date                          sensor.name  pm10.0_atm
2144  06/14/24  Loup Basin Public Health Department  231.757021
2443  06/27/24                     Swnphd-Benklemen  188.977500
6076  12/08/24   #16 - Richardson County Courthouse  200.798396

In [22]:
# Step 1: filter data that has VOC > 25
unhealthy_voc = air_data.loc[air_data['voc'] > 25]

# Step 2: keep only needed columns and sort by date
unhealthy_events = (
    unhealthy_voc[['date', 'sensor.name', 'voc']]
    .sort_values(by='date')
)

unhealthy_events.head(10)

          date                                        sensor.name         voc
6552  01/01/25                                     SWNPHD-Imerial  377.393125
6571  01/01/25                                    Swnphd-ogallala  522.399333
6570  01/01/25  South Heartland District Health Dept. Superior...  199.845625
6569  01/01/25                Loup Basin Public Health Department  193.350875
6568  01/01/25                                           FCHD-YPS  232.136042
6566  01/01/25                                      Swnphd-mccook  440.842000
6565  01/01/25                                         Broken Bow  236.872083
6564  01/01/25                        WCDHD Arthur High School 28  380.885625
6563  01/01/25                         Ainsworth Public School #9  310.367708
6567  01/01/25              Three Rivers Public Health Department  268.037042

In [89]:
# Group air quality data by sensor name and sensor altitude
altitude_air_quality = air_data.groupby(
    ["sensor.name", "sensor.altitude"]
).agg(
    voc_mean=("voc", "mean"),
    pm25_mean=("pm2.5_atm", "mean"),
    pm10_mean=("pm10.0_atm", "mean")
)

# Display summarized air quality values by sensor and altitude
print(altitude_air_quality)

                                                                      voc_mean  \
sensor.name                                        sensor.altitude
#16 - Richardson County Courthouse                 1023              86.758650
#17 - Otoe County                                  1055             251.427296
#18 - Southeast District Health Department- Tec... 1143             196.150771
Ainsworth Public School #9                         2519             219.200274
Broken Bow                                         2582             158.285807
Buffalo County TRPHD #26                           2147             328.835391
ELVPHD Norfolk HD 4                                1522             360.833744
ELVPHD Tekamah HD 3                                1033             221.091595
ELVPHD Wisner HD 5                                 1385             102.291126
FCHD-YPS                                           1639             372.462720
Laurel High School                                 1537             130.631408
Loup Basin Public Health Department                2174             352.833902
Lower Niobrara NRD Butte 10                        1810             227.439379
NCDHD O'Neill #11                                  1990             283.633000
PHS Fairbury JCHL 13                               1438             275.879657
SWNPHD-Imerial                                     3269             285.456355
South Heartland District Health Dept. Hastings ... 1920             305.385314
South Heartland District Health Dept. Superior ... 1597             178.745074
Swnphd-Benklemen                                   3005             336.400969
Swnphd-mccook                                      2576             353.941581
Swnphd-ogallala                                    3220             399.434240
TRPHD Dawson Co. Courthouse 25                     2392             311.912841
TRPHD Harlan Co. Courthouse 24                     1984             209.876608
Three Rivers Public Health Department              1188             370.216208
WCDHD Arthur High School 28                        3661             258.691175
WCDHD City Building                                2800             168.480056
WCDHD Thedford Library 29                          2850             260.536134

                                                                     pm25_mean  \
sensor.name                                        sensor.altitude
#16 - Richardson County Courthouse                 1023             700.127342
#17 - Otoe County                                  1055               9.755345
#18 - Southeast District Health Department- Tec... 1143             613.175352
Ainsworth Public School #9                         2519              10.697058
Broken Bow                                         2582             928.710593
Buffalo County TRPHD #26                           2147               8.479442
ELVPHD Norfolk HD 4                                1522              13.369492
ELVPHD Tekamah HD 3                                1033               9.482822
ELVPHD Wisner HD 5                                 1385              11.154420
FCHD-YPS                                           1639               9.167842
Laurel High School                                 1537               8.635639
Loup Basin Public Health Department                2174               8.561095
Lower Niobrara NRD Butte 10                        1810               8.041274
NCDHD O'Neill #11                                  1990             164.495078
PHS Fairbury JCHL 13                               1438               9.405360
SWNPHD-Imerial                                     3269               6.329091
South Heartland District Health Dept. Hastings ... 1920               8.915233
South Heartland District Health Dept. Superior ... 1597               8.851045
Swnphd-Benklemen                                   3005               7.501374
Swnphd-mccook                                      2576             123.011622
Swnphd-ogallala                                    3220              10.396579
TRPHD Dawson Co. Courthouse 25                     2392              18.080629
TRPHD Harlan Co. Courthouse 24                     1984               7.927510
Three Rivers Public Health Department              1188               9.601760
WCDHD Arthur High School 28                        3661               6.658474
WCDHD City Building                                2800               3.971512
WCDHD Thedford Library 29                          2850               6.219710

                                                                     pm10_mean
sensor.name                                        sensor.altitude
#16 - Richardson County Courthouse                 1023             701.632446
#17 - Otoe County                                  1055              11.671141
#18 - Southeast District Health Department- Tec... 1143             614.227248
Ainsworth Public School #9                         2519              12.390708
Broken Bow                                         2582             929.678512
Buffalo County TRPHD #26                           2147               9.596038
ELVPHD Norfolk HD 4                                1522              15.969341
ELVPHD Tekamah HD 3                                1033              10.683828
ELVPHD Wisner HD 5                                 1385              14.462116
FCHD-YPS                                           1639              11.138241
Laurel High School                                 1537              10.254001
Loup Basin Public Health Department                2174              10.454420
Lower Niobrara NRD Butte 10                        1810               9.365581
NCDHD O'Neill #11                                  1990             166.132578
PHS Fairbury JCHL 13                               1438              11.132398
SWNPHD-Imerial                                     3269               7.281414
South Heartland District Health Dept. Hastings ... 1920               9.852555
South Heartland District Health Dept. Superior ... 1597               9.851113
Swnphd-Benklemen                                   3005               9.041440
Swnphd-mccook                                      2576             124.227336
Swnphd-ogallala                                    3220              11.347889
TRPHD Dawson Co. Courthouse 25                     2392              19.548148
TRPHD Harlan Co. Courthouse 24                     1984               8.944145
Three Rivers Public Health Department              1188              11.226492
WCDHD Arthur High School 28                        3661               7.712941
WCDHD City Building                                2800               4.817597
WCDHD Thedford Library 29                          2850               7.509269

To evaluate whether sensor altitude has an impact on air quality values, pollutant concentrations were grouped by sensor name and sensor altitude. The results show that VOC, PM2.5, and PM10 concentrations vary across sensors located at different elevations. However, no consistent relationship is observed between increasing altitude and lower or higher pollutant concentrations.